AllCops:
  RunRailsCops: true
  Exclude:
    - 'vendor/bundle/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/CaseIndentation:
  IndentOneStep: true

Documentation:
  Enabled: false