AllCops:
  RunRailsCops: true
  Exclude:
    - 'vendor/bundle/**/*'

Metrics/LineLength:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Style/CaseIndentation:
  IndentOneStep: true
